# 02_project_voters.rb

def add_people
	people = []
	people << "Keith,Kelley,Liberal,Arizona".split(",")
	people << "Marie,Spencer,Socialist,New York".split(",")
	people << "Russell,Moore,Socialist,Texas".split(",")
	people << "Martha,Simmons,Neutral,Georgia".split(",")
	people << "Dennis,Schmidt,Liberal,Nebraska".split(",")
	people << "Anthony,Hill,Neutral,Nevada".split(",")
	people << "Joyce,Chavez,Liberal,Ohio".split(",")
	people << "Karen,Henry,Tea party,New York".split(",")
	people << "Lori,Burns,Liberal,Utah".split(",")
	people << "Julia,Palmer,Liberal,California".split(",")
	people << "Carlos,Larson,Liberal,New York".split(",")
	people << "Stephen,Frazier,Tea party,California".split(",")
	people << "Christine,Watson,Neutral,Maryland".split(",")
	people << "Timothy,Gomez,Liberal,Virginia".split(",")
	people << "James,Hayes,Neutral,California".split(",")
	people << "Kathryn,Bishop,Liberal,West Virginia".split(",")
	people << "Lori,Graham,Tea party,Georgia".split(",")
	people << "Anthony,Richards,Conservative,Florida".split(",")
	people << "Andrea,Johnson,Socialist,North Carolina".split(",")
	people << "Joe,Roberts,Neutral,District of Columbia".split(",")
	people << "Ronald,Campbell,Conservative,Texas".split(",")
	people << "Ronald,Simpson,Socialist,District of Columbia".split(",")
	people << "Christina,Mcdonald,Liberal,California".split(",")
	people << "Anthony,Howard,Neutral,Missouri".split(",")
	people << "Jose,Dunn,Neutral,District of Columbia".split(",")
	people << "Dennis,Williams,Conservative,Texas".split(",")
	people << "Linda,Wood,Liberal,New Mexico".split(",")
	people << "Paul,Ramirez,Conservative,Washington".split(",")
	people << "Janet,Gibson,Liberal,Missouri".split(",")
	people << "Lawrence,Austin,Tea party,Texas".split(",")
	people << "Paula,Mills,Socialist,Arizona".split(",")
	people << "Janet,Carpenter,Conservative,North Carolina".split(",")
	people << "Joshua,Cunningham,Socialist,California".split(",")
	people << "Joyce,Gilbert,Socialist,Virginia".split(",")
	people << "Ann,Elliott,Liberal,Michigan".split(",")
	people << "Jerry,Carpenter,Conservative,New York".split(",")
	people << "Marilyn,Lopez,Conservative,Michigan".split(",")
	people << "Carolyn,White,Socialist,Florida".split(",")
	people << "Tina,Lawson,Liberal,District of Columbia".split(",")
	people << "Jacqueline,Stephens,Tea party,Ohio".split(",")
	people << "Dorothy,Chavez,Tea party,Florida".split(",")
	people << "Ralph,Wood,Tea party,Texas".split(",")
	people << "Cynthia,Day,Tea party,Michigan".split(",")
	people << "Pamela,Dean,Socialist,Louisiana".split(",")
	people << "Thomas,Mason,Neutral,Ohio".split(",")
	people << "Nancy,Taylor,Conservative,Illinois".split(",")
	people << "Raymond,Garrett,Socialist,Wisconsin".split(",")
	people << "Michael,Chapman,Conservative,Florida".split(",")
	people << "Joshua,Stone,Neutral,West Virginia".split(",")
	people << "Douglas,Oliver,Liberal,District of Columbia".split(",")
	people << "Irene,Carter,Conservative,Delaware".split(",")
	people << "Christopher,Hawkins,Tea party,Michigan".split(",")
	people << "Paula,Reed,Socialist,Rhode Island".split(",")
	people << "Lori,White,Neutral,Michigan".split(",")
	people << "Aaron,Jenkins,Conservative,Wisconsin".split(",")
	people << "Keith,Chavez,Socialist,Virginia".split(",")
	people << "Gregory,Gibson,Liberal,Alabama".split(",")
	people << "Jennifer,Burke,Neutral,Texas".split(",")
	people << "Timothy,Bell,Socialist,District of Columbia".split(",")
	people << "Rachel,Franklin,Tea party,Minnesota".split(",")
	people << "Paul,Matthews,Tea party,Texas".split(",")
	people << "Chris,Harris,Tea party,California".split(",")
	people << "Brian,Willis,Liberal,California".split(",")
	people << "Scott,Gilbert,Conservative,Texas".split(",")
	people << "Nicole,Simmons,Tea party,Michigan".split(",")
	people << "Julia,Hunter,Neutral,West Virginia".split(",")
	people << "Ronald,Washington,Tea party,Louisiana".split(",")
	people << "Teresa,Bradley,Socialist,Texas".split(",")
	people << "Susan,Evans,Socialist,California".split(",")
	people << "Janet,Cooper,Conservative,Nebraska".split(",")
	people << "Barbara,Stanley,Conservative,Virginia".split(",")
	people << "Linda,Larson,Socialist,Nevada".split(",")
	people << "Betty,Stone,Liberal,Alabama".split(",")
	people << "Phyllis,Day,Socialist,Colorado".split(",")
	people << "Wayne,Ruiz,Conservative,South Carolina".split(",")
	people << "Lois,Olson,Neutral,California".split(",")
	people << "Emily,Cooper,Liberal,Minnesota".split(",")
	people << "Diana,Bailey,Tea party,Pennsylvania".split(",")
	people << "Jerry,Cooper,Liberal,Mississippi".split(",")
	people << "Lois,Turner,Neutral,Indiana".split(",")
	people << "Matthew,Berry,Conservative,Texas".split(",")
	people << "Anthony,Gonzalez,Socialist,Minnesota".split(",")
	people << "Beverly,Gray,Tea party,Georgia".split(",")
	people << "Shawn,Morales,Socialist,California".split(",")
	people << "Shirley,Cole,Tea party,Washington".split(",")
	people << "Kimberly,Simpson,Neutral,Texas".split(",")
	people << "Louise,Roberts,Conservative,Florida".split(",")
	people << "Steve,Sanchez,Liberal,New York".split(",")
	people << "Carlos,Perez,Socialist,District of Columbia".split(",")
	people << "Jimmy,Fox,Conservative,District of Columbia".split(",")
	people << "Johnny,Stone,Conservative,Connecticut".split(",")
	people << "Chris,Rice,Neutral,Alabama".split(",")
	people << "Terry,Fowler,Socialist,California".split(",")
	people << "Kevin,Myers,Neutral,Texas".split(",")
	people << "Bonnie,Garza,Tea party,California".split(",")
	people << "Amy,Martin,Conservative,South Carolina".split(",")
	people << "Ruth,Thomas,Tea party,New York".split(",")
	people << "Ronald,Greene,Socialist,Ohio".split(",")
	people << "Kathryn,Hawkins,Conservative,New Jersey".split(",")
	people << "Julia,Sims,Neutral,California".split(",")
	people << "Doris,Wallace,Socialist,District of Columbia".split(",")
	people << "Margaret,Stephens,Neutral,Missouri".split(",")
	people << "Earl,White,Liberal,Texas".split(",")
	people << "Carl,Romero,Liberal,Kansas".split(",")
	people << "Robert,Perry,Tea party,New Jersey".split(",")
	people << "Pamela,Carpenter,Conservative,California".split(",")
	people << "Nicole,Andrews,Conservative,South Carolina".split(",")
	people << "Johnny,Anderson,Conservative,Michigan".split(",")
	people << "Annie,Sullivan,Socialist,Florida".split(",")
	people << "Gloria,Riley,Conservative,North Carolina".split(",")
	people << "Samuel,Riley,Liberal,Colorado".split(",")
	people << "Julie,Kim,Conservative,Kansas".split(",")
	people << "Brandon,Young,Socialist,Texas".split(",")
	people << "Donna,Myers,Socialist,North Carolina".split(",")
	people << "Billy,Harvey,Liberal,Maryland".split(",")
	people << "Sandra,Morales,Tea party,Ohio".split(",")
	people << "Jeffrey,Wallace,Conservative,Washington".split(",")
	people << "Jack,Dixon,Tea party,District of Columbia".split(",")
	people << "Thomas,Jacobs,Socialist,New York".split(",")
	people << "Mildred,White,Neutral,Connecticut".split(",")
	people << "Mark,Castillo,Liberal,Georgia".split(",")
	people << "Martin,Davis,Socialist,Washington".split(",")
	people << "Beverly,Carpenter,Socialist,Louisiana".split(",")
	people << "Earl,Frazier,Neutral,South Carolina".split(",")
	people << "Nicole,Oliver,Liberal,Texas".split(",")
	people << "Jeffrey,Hunt,Neutral,Indiana".split(",")
	people << "Katherine,Hill,Neutral,California".split(",")
	people << "Susan,Anderson,Liberal,California".split(",")
	people << "Arthur,Richardson,Neutral,Hawaii".split(",")
	people << "Paula,Jones,Tea party,Indiana".split(",")
	people << "Emily,Reed,Conservative,Massachusetts".split(",")
	people << "Brenda,Lee,Neutral,Texas".split(",")
	people << "Deborah,Phillips,Tea party,California".split(",")
	people << "Gerald,Riley,Socialist,Illinois".split(",")
	people << "Ryan,Wheeler,Conservative,Delaware".split(",")
	people << "Anne,Richards,Liberal,South Carolina".split(",")
	people << "Carol,Lynch,Socialist,Texas".split(",")
	people << "Theresa,Alvarez,Conservative,Nebraska".split(",")
	people << "Evelyn,Fields,Liberal,Pennsylvania".split(",")
	people << "Julie,Bennett,Conservative,California".split(",")
	people << "Dennis,Dixon,Neutral,Illinois".split(",")
	people << "Kenneth,Phillips,Conservative,North Carolina".split(",")
	people << "Jeremy,Torres,Liberal,Nevada".split(",")
	people << "Annie,Harvey,Conservative,Oregon".split(",")
	people << "Mildred,Taylor,Tea party,Ohio".split(",")
	people << "Russell,Dean,Socialist,California".split(",")
	people << "Lori,Shaw,Socialist,Tennessee".split(",")
	people << "Sandra,Clark,Socialist,Georgia".split(",")
	people << "Raymond,Hernandez,Conservative,New York".split(",")
	people << "Virginia,Grant,Neutral,New York".split(",")
	people << "Phyllis,Sims,Liberal,District of Columbia".split(",")
	people << "Paula,Jones,Tea party,California".split(",")
	people << "Brian,Powell,Liberal,District of Columbia".split(",")
	people << "Judy,Ellis,Neutral,Virginia".split(",")
	people << "Judith,Medina,Liberal,Tennessee".split(",")
	people << "Beverly,Hall,Conservative,Indiana".split(",")
	people << "Albert,Rogers,Neutral,California".split(",")
	people << "Dorothy,Rose,Socialist,Alabama".split(",")
	people << "Sarah,Fields,Liberal,Texas".split(",")
	people << "Sara,Vasquez,Conservative,Alaska".split(",")
	people << "George,Carter,Liberal,Florida".split(",")
	people << "Cynthia,Harper,Socialist,Indiana".split(",")
	people << "Kathryn,Kim,Socialist,California".split(",")
	people << "Kelly,Cook,Tea party,Alaska".split(",")
	people << "Tammy,Peterson,Conservative,Nebraska".split(",")
	people << "Carol,Lopez,Socialist,Texas".split(",")
	people << "Jason,Lawrence,Socialist,Texas".split(",")
	people << "Chris,Fowler,Neutral,New York".split(",")
	people << "Margaret,Burns,Liberal,California".split(",")
	people << "Susan,Peters,Socialist,Ohio".split(",")
	people << "George,Ryan,Neutral,Minnesota".split(",")
	people << "Cheryl,Burton,Tea party,Montana".split(",")
	people << "Rachel,Lewis,Neutral,Utah".split(",")
	people << "Margaret,Watkins,Conservative,Illinois".split(",")
	people << "Gloria,Howell,Tea party,Alabama".split(",")
	people << "Peter,Williamson,Conservative,Oklahoma".split(",")
	people << "Irene,Cook,Conservative,Virginia".split(",")
	people << "Annie,Peterson,Socialist,Texas".split(",")
	people << "Craig,Hayes,Liberal,Pennsylvania".split(",")
	people << "Patrick,Fuller,Tea party,Washington".split(",")
	people << "Catherine,Ruiz,Socialist,California".split(",")
	people << "Wayne,Arnold,Tea party,Indiana".split(",")
	people << "Lillian,Jenkins,Liberal,Indiana".split(",")
	people << "Emily,Graham,Neutral,Oklahoma".split(",")
	people << "Rose,Gordon,Socialist,Maryland".split(",")
	people << "Pamela,Pierce,Neutral,Indiana".split(",")
	people << "Douglas,Simpson,Conservative,Wisconsin".split(",")
	people << "Steve,Dean,Tea party,Florida".split(",")
	people << "Anthony,Torres,Tea party,Ohio".split(",")
	people << "Gloria,Lopez,Neutral,Arizona".split(",")
	people << "Clarence,Howard,Neutral,Texas".split(",")
	people << "Diana,Woods,Neutral,Arizona".split(",")
	people << "Randy,Crawford,Socialist,Texas".split(",")
	people << "Jennifer,Crawford,Conservative,Virginia".split(",")
	people << "Nicole,Morales,Liberal,Oklahoma".split(",")
	people << "Adam,Oliver,Tea party,Florida".split(",")
	people << "Johnny,Kelly,Conservative,Ohio".split(",")
	people << "William,Morales,Neutral,California".split(",")
	people << "Frances,Matthews,Neutral,Texas".split(",")
	people << "John,Perez,Conservative,Alabama".split(",")
	people << "Sandra,Mendoza,Socialist,Texas".split(",")
	people << "Jose,Reid,Conservative,Georgia".split(",")
	people << "Richard,Hart,Neutral,Mississippi".split(",")
	people << "Sandra,Day,Tea party,Texas".split(",")
	people << "Laura,Hanson,Socialist,Texas".split(",")
	people << "James,Hicks,Tea party,Texas".split(",")
	people << "Carol,Smith,Socialist,California".split(",")
	people << "Linda,Rice,Conservative,Arkansas".split(",")
	people << "Maria,Ross,Neutral,Ohio".split(",")
	people << "Maria,Rice,Socialist,Pennsylvania".split(",")
	people << "Carl,Garrett,Neutral,Alabama".split(",")
	people << "Phillip,Mason,Socialist,New Jersey".split(",")
	people << "Willie,Riley,Tea party,Michigan".split(",")
	people << "Nicole,Nelson,Liberal,Texas".split(",")
	people << "Rachel,Webb,Socialist,Texas".split(",")
	people << "Mark,Bishop,Neutral,Colorado".split(",")
	people << "Julie,Fox,Conservative,Nebraska".split(",")
	people << "Andrea,Ford,Neutral,Florida".split(",")
	people << "Joyce,Gilbert,Neutral,Minnesota".split(",")
	people << "Rachel,Larson,Neutral,Florida".split(",")
	people << "George,Freeman,Conservative,California".split(",")
	people << "Marie,Wheeler,Liberal,Texas".split(",")
	people << "Ann,Taylor,Neutral,Ohio".split(",")
	people << "David,Jenkins,Socialist,Kansas".split(",")
	people << "Katherine,Jordan,Neutral,District of Columbia".split(",")
	people << "Angela,Owens,Tea party,Pennsylvania".split(",")
	people << "Peter,Banks,Conservative,New York".split(",")
	people << "Tina,Martinez,Neutral,Washington".split(",")
	people << "Henry,Fowler,Tea party,West Virginia".split(",")
	people << "Linda,Lawrence,Tea party,District of Columbia".split(",")
	people << "Samuel,Stewart,Liberal,Hawaii".split(",")
	people << "Shirley,Armstrong,Tea party,Minnesota".split(",")
	people << "Alice,Holmes,Tea party,Virginia".split(",")
	people << "Bruce,Daniels,Liberal,Washington".split(",")
	people << "Jose,Walker,Conservative,Texas".split(",")
	people << "Russell,Franklin,Tea party,Delaware".split(",")
	people << "Frances,Nguyen,Neutral,Illinois".split(",")
	people << "Rachel,Robertson,Conservative,Florida".split(",")
	people << "David,Ortiz,Neutral,New York".split(",")
	people << "Frank,King,Conservative,Pennsylvania".split(",")
	people << "Raymond,Gardner,Conservative,South Carolina".split(",")
	people << "Eric,Gutierrez,Neutral,Texas".split(",")
	people << "Steven,Moreno,Liberal,California".split(",")
	people << "Janet,Morris,Liberal,Florida".split(",")
	people << "Brian,Day,Liberal,District of Columbia".split(",")
	people << "Steven,Fowler,Conservative,District of Columbia".split(",")
	people << "Brandon,Fields,Conservative,Georgia".split(",")
	people << "Teresa,Rivera,Socialist,Montana".split(",")
	people << "Doris,Hicks,Tea party,Indiana".split(",")
	people << "Sarah,King,Conservative,Kansas".split(",")
	people << "Katherine,Sullivan,Liberal,Texas".split(",")
	people << "Martha,Meyer,Liberal,Illinois".split(",")
	people << "Brandon,Roberts,Neutral,Texas".split(",")
	people << "Helen,Grant,Conservative,Florida".split(",")
	people << "Anthony,Armstrong,Socialist,Wyoming".split(",")
	people << "Scott,Harper,Socialist,Indiana".split(",")
	people << "Sharon,Gardner,Liberal,North Carolina".split(",")
	people << "Carl,Nguyen,Liberal,Texas".split(",")
	people << "Philip,Henry,Tea party,District of Columbia".split(",")
	people << "Gerald,Jacobs,Liberal,Illinois".split(",")
	people << "Donald,Hill,Conservative,Nebraska".split(",")
	people << "Bruce,Jackson,Liberal,Indiana".split(",")
	people << "Catherine,Arnold,Tea party,Alabama".split(",")
	people << "Gloria,Schmidt,Conservative,Massachusetts".split(",")
	people << "Kathryn,Thomas,Tea party,Massachusetts".split(",")
	people << "Helen,Perez,Conservative,Texas".split(",")
	people << "Norma,Harris,Tea party,Georgia".split(",")
	people << "Earl,Morales,Liberal,Ohio".split(",")
	people << "Billy,Henry,Conservative,New York".split(",")
	people << "Joan,Snyder,Neutral,Kentucky".split(",")
	people << "Keith,Kennedy,Liberal,Texas".split(",")
	people << "Albert,Collins,Neutral,California".split(",")
	people << "Jacqueline,Olson,Tea party,Alabama".split(",")
	people << "Eugene,Collins,Conservative,Arizona".split(",")
	people << "Antonio,Myers,Conservative,Missouri".split(",")
	people << "Nicole,Palmer,Neutral,Minnesota".split(",")
	people << "Martha,Armstrong,Liberal,California".split(",")
	people << "Harold,Lynch,Tea party,Alabama".split(",")
	people << "Johnny,Palmer,Liberal,Florida".split(",")
	people << "Anthony,Nichols,Conservative,Michigan".split(",")
	people << "Jane,Hunter,Liberal,Iowa".split(",")
	people << "Keith,Simmons,Conservative,California".split(",")
	people << "Russell,Palmer,Liberal,Tennessee".split(",")
	people << "Jack,Coleman,Tea party,Nevada".split(",")
	people << "Gerald,Lopez,Tea party,Florida".split(",")
	people << "Anna,Murphy,Socialist,Florida".split(",")
	people << "Timothy,Wells,Socialist,California".split(",")
	people << "Patrick,Ferguson,Socialist,Texas".split(",")
	people << "Adam,Thompson,Conservative,California".split(",")
	people << "Jose,Wagner,Neutral,District of Columbia".split(",")
	people << "Tina,Lewis,Socialist,District of Columbia".split(",")
	people << "Andrea,Watson,Socialist,California".split(",")
	people << "Paul,Diaz,Liberal,Florida".split(",")
	people << "Lois,Lewis,Liberal,Minnesota".split(",")
	people << "Peter,Adams,Liberal,Texas".split(",")
	people << "William,Daniels,Liberal,Arizona".split(",")
	people << "Albert,Perez,Neutral,Mississippi".split(",")
	people << "Michelle,Harvey,Tea party,New York".split(",")
	people << "Gloria,Olson,Conservative,California".split(",")
	people << "Kathryn,Foster,Conservative,Ohio".split(",")
	people << "Justin,Peters,Conservative,Nevada".split(",")
	people << "Melissa,Moreno,Neutral,South Carolina".split(",")
	people << "Roger,Sanchez,Tea party,Arizona".split(",")
	people << "Wayne,Peters,Tea party,New York".split(",")
	people << "Karen,Dean,Tea party,California".split(",")
	people << "Donald,Green,Conservative,Arizona".split(",")
	people << "Earl,Hawkins,Neutral,Kansas".split(",")
	people << "Jane,Chavez,Conservative,Colorado".split(",")
	people << "Gloria,Reynolds,Liberal,Florida".split(",")
	people << "Sara,Montgomery,Tea party,Wisconsin".split(",")
	people << "Linda,Robertson,Tea party,Massachusetts".split(",")
	people << "Scott,Alvarez,Liberal,Missouri".split(",")
	people << "Christopher,Gordon,Neutral,Indiana".split(",")
	people << "Randy,Lawrence,Socialist,Texas".split(",")
	people << "Adam,Matthews,Socialist,Hawaii".split(",")
	people << "Susan,Long,Neutral,West Virginia".split(",")
	people << "Elizabeth,Barnes,Conservative,Texas".split(",")
	people << "Dorothy,Frazier,Liberal,Pennsylvania".split(",")
	people << "Benjamin,Hill,Liberal,Oregon".split(",")
	people << "Nancy,Carroll,Tea party,Texas".split(",")
	people << "William,Lane,Conservative,Virginia".split(",")
	people << "Alice,Washington,Conservative,Missouri".split(",")
	people << "Philip,Barnes,Neutral,Indiana".split(",")
	people << "Susan,Washington,Neutral,Georgia".split(",")
	people << "Tina,Mendoza,Tea party,Indiana".split(",")
	people << "Earl,Long,Socialist,Nevada".split(",")
	people << "William,Kennedy,Tea party,Louisiana".split(",")
	people << "Paula,Ferguson,Neutral,Wisconsin".split(",")
	people << "Billy,Ortiz,Tea party,Kentucky".split(",")
	people << "Robert,Meyer,Socialist,Texas".split(",")
	people << "Mary,Stevens,Liberal,New York".split(",")
	people << "Pamela,Chapman,Socialist,Minnesota".split(",")
	people << "Scott,Ruiz,Liberal,West Virginia".split(",")
	people << "Mary,Howell,Conservative,California".split(",")
	people << "Ronald,Carpenter,Conservative,South Carolina".split(",")
	people << "Ralph,Pierce,Tea party,Michigan".split(",")
	people << "Kathy,Jenkins,Tea party,Utah".split(",")
	people << "Benjamin,Freeman,Liberal,California".split(",")
	people << "Robin,Johnston,Neutral,Oregon".split(",")
	people << "Ronald,Dunn,Socialist,California".split(",")
	people << "Mildred,Reyes,Socialist,New York".split(",")
	people << "Charles,Harper,Neutral,Washington".split(",")
	people << "Nancy,Wells,Liberal,Pennsylvania".split(",")
	people << "Rachel,Welch,Neutral,Mississippi".split(",")
	people << "Kenneth,Hughes,Conservative,Colorado".split(",")
	people << "Jessica,Gonzalez,Neutral,Washington".split(",")
	people << "Gregory,Boyd,Conservative,Ohio".split(",")
	people << "Jimmy,Stone,Liberal,Indiana".split(",")
	people << "Kimberly,Fernandez,Neutral,California".split(",")
	people << "Linda,Henderson,Liberal,Indiana".split(",")
	people << "Ruth,Lawrence,Socialist,New Jersey".split(",")
	people << "Betty,Fuller,Conservative,California".split(",")
	people << "Eric,Russell,Conservative,California".split(",")
	people << "Kathy,Bell,Conservative,Kentucky".split(",")
	people << "Katherine,Henry,Socialist,Florida".split(",")
	people << "Ryan,Graham,Conservative,New York".split(",")
	people << "Emily,Perez,Neutral,Kansas".split(",")
	people << "Nicole,Garrett,Socialist,Indiana".split(",")
	people << "Ryan,Nichols,Liberal,California".split(",")
	people << "Denise,Murray,Socialist,Idaho".split(",")
	people << "Angela,Hart,Conservative,Colorado".split(",")
	people << "Ryan,Ramos,Tea party,California".split(",")
	people << "Stephanie,Bradley,Conservative,California".split(",")
	people << "Ronald,James,Socialist,Texas".split(",")
	people << "George,Parker,Conservative,Texas".split(",")
	people << "Cynthia,Palmer,Liberal,Florida".split(",")
	people << "Anthony,Henry,Neutral,Georgia".split(",")
	people << "Linda,Rose,Liberal,Florida".split(",")
	people << "Brian,Andrews,Neutral,New Mexico".split(",")
	people << "Beverly,Stanley,Tea party,New York".split(",")
	people << "Deborah,Larson,Liberal,Georgia".split(",")
	people << "Jimmy,Henderson,Neutral,Colorado".split(",")
	people << "Nancy,Freeman,Socialist,Florida".split(",")
	people << "John,Ferguson,Liberal,Michigan".split(",")
	people << "Steven,Collins,Liberal,Texas".split(",")
	people << "Nicole,Lewis,Liberal,Missouri".split(",")
	people << "Larry,Cole,Liberal,District of Columbia".split(",")
	people << "Harry,Day,Conservative,California".split(",")
	people << "Katherine,Washington,Tea party,Indiana".split(",")
	people << "Betty,Gonzales,Tea party,Texas".split(",")
	people << "Stephanie,Roberts,Liberal,Louisiana".split(",")
	people << "Sharon,Mccoy,Tea party,Michigan".split(",")
	people << "Phillip,Young,Tea party,Pennsylvania".split(",")
	people << "Ronald,Duncan,Tea party,Arizona".split(",")
	people << "Stephen,Gilbert,Conservative,District of Columbia".split(",")
	people << "Shirley,Cruz,Socialist,Louisiana".split(",")
	people << "Paul,Hansen,Conservative,Arkansas".split(",")
	people << "Roy,Sims,Conservative,Texas".split(",")
	people << "Denise,Sanders,Conservative,Florida".split(",")
	people << "Thomas,Collins,Conservative,Florida".split(",")
	people << "Carolyn,Perkins,Socialist,California".split(",")
	people << "Ralph,Romero,Liberal,Texas".split(",")
	people << "Eric,Rice,Liberal,California".split(",")
	people << "Kathryn,Duncan,Tea party,New York".split(",")
	people << "Michael,Long,Liberal,Michigan".split(",")
	people << "Janice,Moreno,Conservative,Tennessee".split(",")
	people << "Joshua,Robinson,Conservative,Michigan".split(",")
	people << "Stephen,Henry,Conservative,Colorado".split(",")
	people << "Alan,Stone,Neutral,Texas".split(",")
	people << "Terry,Sanders,Liberal,District of Columbia".split(",")
	people << "Carl,Duncan,Socialist,Louisiana".split(",")
	people << "Rachel,Dean,Tea party,Texas".split(",")
	people << "Robert,Ross,Liberal,New York".split(",")
	people << "Pamela,Stewart,Neutral,Pennsylvania".split(",")
	people << "Julie,Hart,Socialist,California".split(",")
	people << "Doris,Hill,Neutral,Nevada".split(",")
	people << "Todd,Burton,Tea party,Texas".split(",")
	people << "Judy,Perez,Socialist,Virginia".split(",")
	people << "Lisa,Cox,Liberal,Louisiana".split(",")
	people << "Marilyn,Sullivan,Socialist,Alabama".split(",")
	people << "Kimberly,Baker,Tea party,District of Columbia".split(",")
	people << "Shawn,Riley,Socialist,Utah".split(",")
	people << "Albert,Lynch,Socialist,Illinois".split(",")
	people << "Christine,Freeman,Socialist,New York".split(",")
	people << "Bobby,White,Conservative,Arkansas".split(",")
	people << "Elizabeth,Reed,Socialist,Oregon".split(",")
	people << "Joe,Wheeler,Conservative,Massachusetts".split(",")
	people << "Lawrence,Hicks,Neutral,New York".split(",")
	people << "Sean,Lewis,Tea party,Oregon".split(",")
	people << "Steven,Reyes,Conservative,Washington".split(",")
	people << "Chris,Welch,Conservative,Virginia".split(",")
	people << "Phyllis,Hansen,Tea party,Louisiana".split(",")
	people << "Robin,Reid,Conservative,Ohio".split(",")
	people << "Timothy,Schmidt,Liberal,Texas".split(",")
	people << "Mark,Moreno,Tea party,New Mexico".split(",")
	people << "Janet,Wilson,Liberal,Georgia".split(",")
	people << "Louise,Miller,Liberal,Georgia".split(",")
	people << "Amanda,Duncan,Tea party,Ohio".split(",")
	people << "Shirley,Olson,Conservative,Colorado".split(",")
	people << "Billy,Martin,Conservative,Arizona".split(",")
	people << "Katherine,Wagner,Neutral,California".split(",")
	people << "Wanda,Garcia,Socialist,Florida".split(",")
	people << "Carlos,Robinson,Socialist,Pennsylvania".split(",")
	people << "Albert,Snyder,Conservative,Florida".split(",")
	people << "Dorothy,Miller,Neutral,Louisiana".split(",")
	people << "Nicholas,Owens,Conservative,California".split(",")
	people << "Helen,Oliver,Socialist,District of Columbia".split(",")
	people << "Frank,Larson,Tea party,New York".split(",")
	people << "Laura,Burton,Socialist,Texas".split(",")
	people << "David,Scott,Tea party,Massachusetts".split(",")
	people << "Peter,Myers,Liberal,Texas".split(",")
	people << "Terry,Lawson,Tea party,Ohio".split(",")
	people << "Joe,Castillo,Neutral,Nebraska".split(",")
	people << "Ruby,Perry,Liberal,Oregon".split(",")
	people << "Juan,Williams,Neutral,Indiana".split(",")
	people << "Jose,Robertson,Liberal,Ohio".split(",")
	people << "Carl,Little,Socialist,Utah".split(",")
	people << "Arthur,Hunt,Liberal,Colorado".split(",")
	people << "Catherine,Adams,Tea party,California".split(",")
	people << "Teresa,Riley,Neutral,Florida".split(",")
	people << "Rebecca,Hayes,Conservative,Nevada".split(",")
	people << "Carol,Murray,Tea party,District of Columbia".split(",")
	people << "Denise,Sullivan,Liberal,Texas".split(",")
	people << "Teresa,Peters,Liberal,Ohio".split(",")
	people << "Virginia,Fowler,Tea party,Ohio".split(",")
	people << "Donald,Ferguson,Neutral,Maryland".split(",")
	people << "Donald,Peterson,Tea party,Missouri".split(",")
	people << "Russell,Ellis,Socialist,Georgia".split(",")
	people << "Jimmy,Thompson,Conservative,Florida".split(",")
	people << "Albert,Hicks,Conservative,Colorado".split(",")
	people << "Carl,Roberts,Neutral,Tennessee".split(",")
	people << "Andrew,Evans,Neutral,North Carolina".split(",")
	people << "Maria,Howell,Neutral,Oklahoma".split(",")
	people << "Thomas,Gardner,Tea party,New York".split(",")
	people << "Melissa,Richards,Conservative,Pennsylvania".split(",")
	people << "Michelle,Elliott,Tea party,Kansas".split(",")
	people << "William,Chavez,Conservative,New York".split(",")
	people << "Antonio,Elliott,Neutral,Florida".split(",")
	people << "Nicholas,Gonzalez,Conservative,North Carolina".split(",")
	people << "Cheryl,Fowler,Conservative,Florida".split(",")
	people << "Victor,Myers,Socialist,Minnesota".split(",")
	people << "Amy,Coleman,Neutral,Texas".split(",")
	people << "Jesse,Willis,Tea party,District of Columbia".split(",")
	people << "Doris,Cruz,Liberal,Michigan".split(",")
	people << "James,Bradley,Tea party,California".split(",")
	people << "Emily,Willis,Socialist,Florida".split(",")
	people << "Phillip,Moreno,Conservative,North Carolina".split(",")
	people << "Paula,Spencer,Conservative,Texas".split(",")
	people << "Evelyn,Willis,Socialist,Minnesota".split(",")
	people << "Benjamin,Harris,Conservative,Michigan".split(",")
	people << "Antonio,Wheeler,Conservative,Ohio".split(",")
	people << "Kathy,Simmons,Socialist,Alabama".split(",")
	people << "Walter,Armstrong,Conservative,Florida".split(",")
	people << "Irene,Ryan,Neutral,Pennsylvania".split(",")
	people << "Gary,Ryan,Conservative,California".split(",")
	people << "Dorothy,Fisher,Socialist,Texas".split(",")
	people << "Ann,Bennett,Liberal,Nebraska".split(",")
	people << "Lori,Allen,Tea party,Virginia".split(",")
	people << "Joan,Armstrong,Neutral,Indiana".split(",")
	people << "Shawn,Harvey,Neutral,Virginia".split(",")
	people << "Timothy,Holmes,Socialist,New York".split(",")
	people << "Scott,Kim,Liberal,Utah".split(",")
	people << "Sharon,Wright,Neutral,Texas".split(",")
	people << "Justin,Hill,Tea party,North Carolina".split(",")
	people << "Janice,Long,Conservative,Virginia".split(",")
	people << "Betty,Duncan,Socialist,Virginia".split(",")
	people << "Philip,Wagner,Socialist,New York".split(",")
	people << "Margaret,Wallace,Neutral,New York".split(",")
	people << "Chris,Little,Conservative,Colorado".split(",")
	people << "Phillip,Gardner,Liberal,Texas".split(",")
	people << "Samuel,Simmons,Neutral,Texas".split(",")
	people << "Christine,Scott,Conservative,New York".split(",")
	people << "Shirley,Freeman,Neutral,New Jersey".split(",")
	people << "Pamela,Arnold,Tea party,North Carolina".split(",")
	people << "Randy,Howell,Neutral,Iowa".split(",")
	people << "Pamela,Harvey,Socialist,Maryland".split(",")
	people << "Gregory,Collins,Neutral,Texas".split(",")
	people << "Rachel,Ramirez,Tea party,Michigan".split(",")
	people << "Sara,Kelley,Socialist,Michigan".split(",")
	people << "Janet,Fuller,Tea party,Nevada".split(",")
	people << "Joyce,George,Socialist,North Carolina".split(",")
	people << "Pamela,Gordon,Tea party,Michigan".split(",")
	people << "Todd,Butler,Tea party,Texas".split(",")
	people << "Shirley,Moore,Liberal,Ohio".split(",")
	people << "Ernest,Dunn,Tea party,Alabama".split(",")
	people << "Jimmy,Morris,Liberal,Florida".split(",")
	people << "Adam,Stewart,Liberal,Arkansas".split(",")
	people << "Heather,Garcia,Liberal,New York".split(",")
	people << "Marilyn,Bell,Neutral,Florida".split(",")
	people << "Joan,Jenkins,Liberal,Minnesota".split(",")
	people << "Lisa,Nelson,Liberal,California".split(",")
	people << "Gloria,Wilson,Conservative,Florida".split(",")
	people << "Douglas,Gonzalez,Neutral,New York".split(",")
	people << "Ruth,Carpenter,Conservative,Minnesota".split(",")
	people << "Marilyn,Romero,Neutral,California".split(",")
	people << "Timothy,Griffin,Liberal,Alabama".split(",")
	people << "Earl,Hayes,Liberal,Texas".split(",")
	people << "Jeremy,Stewart,Conservative,Connecticut".split(",")
	people << "Ralph,Ross,Socialist,California".split(",")
	people << "Roy,Woods,Tea party,Texas".split(",")
	people << "Antonio,Fields,Neutral,Connecticut".split(",")
	people << "Michelle,Kelley,Socialist,Texas".split(",")
	people << "Thomas,Gonzales,Tea party,Michigan".split(",")
	people << "Frances,Jackson,Tea party,Maryland".split(",")
	people << "Ronald,Murray,Socialist,Montana".split(",")
	people << "Lois,Larson,Socialist,Virginia".split(",")
	people << "Ronald,Andrews,Conservative,California".split(",")
	people << "Brandon,Lawrence,Conservative,Florida".split(",")
	people << "Barbara,Alvarez,Tea party,Missouri".split(",")
	people << "Heather,Pierce,Neutral,Indiana".split(",")
	people << "Stephen,Hart,Neutral,Florida".split(",")
	people << "Henry,Gonzalez,Socialist,Pennsylvania".split(",")
	people << "Jeremy,Wells,Socialist,New York".split(",")
	people << "Diana,Mcdonald,Tea party,Wisconsin".split(",")
	people << "Edward,Stephens,Conservative,District of Columbia".split(",")
	people << "Pamela,Burke,Conservative,Georgia".split(",")
	people << "Christina,Harvey,Neutral,Florida".split(",")
	people << "Justin,Daniels,Tea party,Florida".split(",")
	people << "Diane,Mccoy,Conservative,Texas".split(",")
	people << "David,Mcdonald,Conservative,Missouri".split(",")
	people << "Jonathan,Mcdonald,Liberal,New Mexico".split(",")
	people << "Tina,Larson,Tea party,South Carolina".split(",")
	people << "Ruth,Harper,Neutral,Virginia".split(",")
	people << "Margaret,Clark,Neutral,New York".split(",")
	people << "Christopher,Harris,Tea party,Ohio".split(",")
	people << "Janet,Day,Tea party,Florida".split(",")
	people << "Joseph,Johnson,Neutral,Georgia".split(",")
	people << "Ryan,West,Tea party,Missouri".split(",")
	people << "Roger,Coleman,Tea party,Florida".split(",")
	people << "Bobby,Wells,Liberal,Florida".split(",")
	people << "Christopher,Hernandez,Conservative,Texas".split(",")
	people << "Earl,Arnold,Neutral,North Carolina".split(",")
	people << "Henry,Howell,Neutral,Kansas".split(",")
	people << "Carolyn,Perkins,Conservative,Massachusetts".split(",")
	people << "Anne,Lee,Conservative,Georgia".split(",")
	people << "Raymond,Rogers,Liberal,Texas".split(",")
	people << "Phillip,Henderson,Conservative,Michigan".split(",")
	people << "Gloria,Graham,Neutral,California".split(",")
	people << "Denise,Mason,Liberal,Georgia".split(",")
	people << "Lisa,Chavez,Neutral,Ohio".split(",")
	people << "Sara,Burns,Conservative,Arizona".split(",")
	people << "Jean,Sanders,Neutral,Georgia".split(",")
	people << "Paula,Barnes,Socialist,Florida".split(",")
	people << "Daniel,Hicks,Tea party,New York".split(",")
	people << "Sean,Sanchez,Neutral,Colorado".split(",")
	people << "Angela,West,Tea party,California".split(",")
	people << "Eric,Hamilton,Liberal,New Mexico".split(",")
	people << "Jerry,Howard,Socialist,Florida".split(",")
	people << "Phillip,Welch,Tea party,Nevada".split(",")
	people << "Paul,Gutierrez,Tea party,Tennessee".split(",")
	people << "Joseph,Perkins,Neutral,Kansas".split(",")
	people << "Martha,Dixon,Conservative,Louisiana".split(",")
	people << "Patrick,Dunn,Conservative,California".split(",")
	people << "Carolyn,Wood,Conservative,Ohio".split(",")
	people << "Jack,Williams,Liberal,California".split(",")
	people << "Louise,Martin,Socialist,Iowa".split(",")
	people << "Beverly,Payne,Tea party,Washington".split(",")
	people << "Mary,Bell,Tea party,Texas".split(",")
	people << "Kevin,Richardson,Neutral,Texas".split(",")
	people << "Helen,Medina,Socialist,Nevada".split(",")
	people << "Wanda,Gonzalez,Socialist,Ohio".split(",")
	people << "Rebecca,Peters,Tea party,Kentucky".split(",")
	people << "Larry,Cooper,Conservative,South Carolina".split(",")
	people << "Cheryl,Diaz,Socialist,Georgia".split(",")
	people << "Jimmy,Lane,Conservative,Maryland".split(",")
	people << "Janet,Rogers,Socialist,Louisiana".split(",")
	people << "Wanda,Ross,Conservative,California".split(",")
	people << "Beverly,Martinez,Tea party,New York".split(",")
	people << "Anthony,Martinez,Tea party,Florida".split(",")
	people << "Nancy,Morrison,Socialist,Missouri".split(",")
	people << "Patricia,Sims,Socialist,California".split(",")
	people << "Roger,Mccoy,Socialist,Colorado".split(",")
	people << "Heather,Hall,Liberal,South Carolina".split(",")
	people << "Donna,Fields,Conservative,Louisiana".split(",")
	people << "Jeremy,Johnston,Socialist,Tennessee".split(",")
	people << "John,Miller,Conservative,New York".split(",")
	people << "Ronald,Taylor,Tea party,Virginia".split(",")
	people << "Ryan,Ray,Liberal,Texas".split(",")
	people << "Jonathan,Bennett,Liberal,West Virginia".split(",")
	people << "Julie,Harris,Tea party,Utah".split(",")
	people << "Phyllis,Lawson,Liberal,New York".split(",")
	people << "William,Perry,Conservative,New York".split(",")
	people << "Angela,Johnson,Conservative,Idaho".split(",")
	people << "Martha,Carr,Tea party,Tennessee".split(",")
	people << "George,Lynch,Neutral,Texas".split(",")
	people << "Wanda,Wells,Socialist,Texas".split(",")
	people << "Paul,Hayes,Conservative,Michigan".split(",")
	people << "Paula,Burke,Socialist,Kansas".split(",")
	people << "Lawrence,Harvey,Conservative,Texas".split(",")
	people << "Teresa,Berry,Neutral,Nevada".split(",")
	people << "Frances,Barnes,Neutral,Maryland".split(",")
	people << "Anne,Hawkins,Neutral,North Carolina".split(",")
	people << "Jacqueline,Ross,Conservative,Ohio".split(",")
	people << "Denise,Rivera,Tea party,West Virginia".split(",")
	people << "Louis,Martin,Neutral,Utah".split(",")
	people << "Paula,Jordan,Neutral,California".split(",")
	people << "Pamela,Ruiz,Conservative,Maryland".split(",")
	people << "Bobby,Grant,Conservative,Nebraska".split(",")
	people << "Shawn,Jacobs,Conservative,Ohio".split(",")
	people << "Louis,Martinez,Socialist,Florida".split(",")
	people << "Lori,Carpenter,Neutral,Ohio".split(",")
	people << "Robin,Murray,Tea party,Indiana".split(",")
	people << "Earl,Hart,Conservative,California".split(",")
	people << "Stephen,Campbell,Conservative,Michigan".split(",")
	people << "Rose,Diaz,Socialist,Kentucky".split(",")
	people << "Henry,Bailey,Liberal,Louisiana".split(",")
	people << "Gloria,Allen,Tea party,Wisconsin".split(",")
	people << "Irene,Stanley,Liberal,California".split(",")
	people << "Jeffrey,Jones,Liberal,Colorado".split(",")
	people << "Phyllis,Lawson,Socialist,Virginia".split(",")
	people << "Scott,Rose,Liberal,Virginia".split(",")
	people << "William,Lopez,Socialist,Delaware".split(",")
	people << "Cheryl,Armstrong,Socialist,New York".split(",")
	people << "Adam,Lewis,Neutral,Maryland".split(",")
	people << "James,Webb,Socialist,Tennessee".split(",")
	people << "Denise,Watkins,Neutral,Missouri".split(",")
	people << "Karen,Snyder,Socialist,California".split(",")
	people << "Kathleen,Lane,Conservative,Florida".split(",")
	people << "Elizabeth,Bowman,Socialist,Ohio".split(",")
	people << "Joseph,Davis,Tea party,Indiana".split(",")
	people << "Diane,Ortiz,Neutral,Iowa".split(",")
	people << "Gregory,Harrison,Liberal,Idaho".split(",")
	people << "Gregory,Hansen,Neutral,Michigan".split(",")
	people << "Doris,Bailey,Socialist,New Jersey".split(",")
	people << "Ruth,Jones,Liberal,Connecticut".split(",")
	people << "Ronald,Long,Socialist,New York".split(",")
	people << "Nicole,Harrison,Tea party,California".split(",")
	people << "Samuel,Nguyen,Liberal,Missouri".split(",")
	people << "Laura,Fisher,Conservative,Montana".split(",")
	people << "Norma,Pierce,Neutral,Delaware".split(",")
	people << "Christopher,Day,Liberal,Virginia".split(",")
	people << "Anna,Snyder,Socialist,Virginia".split(",")
	people << "Kathy,Olson,Conservative,California".split(",")
	people << "Diane,Anderson,Conservative,Nevada".split(",")
	people << "Louise,Anderson,Conservative,Florida".split(",")
	people << "Albert,Boyd,Socialist,Texas".split(",")
	people << "Louise,Porter,Socialist,California".split(",")
	people << "Katherine,Price,Socialist,Indiana".split(",")
	people << "Roger,Shaw,Socialist,North Carolina".split(",")
	people << "Ernest,Jordan,Conservative,California".split(",")
	people << "Dennis,Bell,Tea party,Utah".split(",")
	people << "Gary,Ellis,Conservative,Ohio".split(",")
	people << "Kathy,Black,Liberal,California".split(",")
	people << "Gloria,Long,Socialist,Wisconsin".split(",")
	people << "Jonathan,Payne,Socialist,Michigan".split(",")
	people << "Patrick,Rice,Tea party,Alabama".split(",")
	people << "Jason,Hunter,Conservative,Kentucky".split(",")
	people << "Benjamin,Parker,Liberal,Kentucky".split(",")
	people << "Fred,Hawkins,Conservative,California".split(",")
	people << "Beverly,Stone,Conservative,District of Columbia".split(",")
	people << "Aaron,Barnes,Neutral,California".split(",")
	people << "Jeremy,Welch,Neutral,Utah".split(",")
	people << "Frank,Coleman,Conservative,Alabama".split(",")
	people << "Patrick,Nelson,Neutral,Florida".split(",")
	people << "Diana,Reed,Neutral,Nebraska".split(",")
	people << "Denise,Little,Neutral,Indiana".split(",")
	people << "Judy,Warren,Tea party,Alabama".split(",")
	people << "Jeffrey,Hill,Conservative,District of Columbia".split(",")
	people << "Robert,Martin,Conservative,Texas".split(",")
	people << "Wayne,Fisher,Socialist,Florida".split(",")
	people << "Helen,Graham,Conservative,New Mexico".split(",")
	people << "Michelle,Long,Tea party,Illinois".split(",")
	people << "Mildred,Fields,Socialist,California".split(",")
	people << "Louise,Powell,Liberal,New Jersey".split(",")
	people << "David,Dunn,Socialist,Florida".split(",")
	people << "Wayne,Rose,Conservative,Georgia".split(",")
	people << "Donna,Wilson,Socialist,West Virginia".split(",")
	people << "Paul,Robertson,Socialist,California".split(",")
	people << "Kelly,Alexander,Socialist,Ohio".split(",")
	people << "Martha,Burton,Socialist,California".split(",")
	people << "Julie,Wright,Neutral,New York".split(",")
	people << "Edward,Adams,Socialist,Ohio".split(",")
	people << "Marie,Spencer,Socialist,Missouri".split(",")
	people << "Kevin,Fisher,Conservative,Rhode Island".split(",")
	people << "Charles,Hamilton,Tea party,Tennessee".split(",")
	people << "Joyce,Kennedy,Tea party,Texas".split(",")
	people << "Michelle,Campbell,Tea party,New York".split(",")
	people << "Mildred,Butler,Tea party,Florida".split(",")
	people << "William,Hansen,Socialist,Florida".split(",")
	people << "Wanda,Campbell,Liberal,Colorado".split(",")
	people << "Gloria,Morrison,Socialist,Florida".split(",")
	people << "Wanda,Coleman,Socialist,California".split(",")
	people << "Louis,Jones,Conservative,District of Columbia".split(",")
	people << "Walter,Hansen,Neutral,Pennsylvania".split(",")
	people << "Thomas,Gray,Neutral,Tennessee".split(",")
	people << "Daniel,Kelly,Liberal,Louisiana".split(",")
	people << "Doris,Porter,Liberal,Oregon".split(",")
	people << "Christine,Ray,Liberal,Indiana".split(",")
	people << "Teresa,Kelly,Conservative,Georgia".split(",")
	people << "Jennifer,Gordon,Tea party,Texas".split(",")
	people << "Marie,Hicks,Neutral,Florida".split(",")
	people << "Harry,Gilbert,Liberal,Idaho".split(",")
	people << "Carl,Palmer,Socialist,Florida".split(",")
	people << "Roy,Ellis,Liberal,Virginia".split(",")
	people << "Dennis,Scott,Liberal,District of Columbia".split(",")
	people << "Norma,Long,Tea party,Ohio".split(",")
	people << "Kathryn,Wright,Tea party,Texas".split(",")
	people << "Steven,Johnston,Socialist,Ohio".split(",")
	people << "Henry,Ortiz,Conservative,Delaware".split(",")
	people << "Michelle,Burke,Conservative,Texas".split(",")
	people << "Deborah,Freeman,Neutral,Texas".split(",")
	people << "Ann,Edwards,Conservative,Florida".split(",")
	people << "Peter,Hamilton,Neutral,Texas".split(",")
	people << "Martin,Mendoza,Conservative,New York".split(",")
	people << "Rachel,Green,Liberal,Kentucky".split(",")
	people << "Jack,Morris,Socialist,District of Columbia".split(",")
	people << "Gerald,Bell,Tea party,District of Columbia".split(",")
	people << "Cynthia,Hicks,Socialist,Pennsylvania".split(",")
	people << "Justin,Webb,Conservative,Nevada".split(",")
	people << "Katherine,Lane,Conservative,Arizona".split(",")
	people << "Evelyn,Dunn,Neutral,Arizona".split(",")
	people << "Karen,Sims,Neutral,Florida".split(",")
	people << "Antonio,Lee,Tea party,Utah".split(",")
	people << "Benjamin,Hughes,Neutral,Virginia".split(",")
	people << "Kimberly,Collins,Socialist,Texas".split(",")
	people << "Katherine,Gomez,Neutral,Colorado".split(",")
	people << "Sara,Hawkins,Neutral,Indiana".split(",")
	people << "Sharon,Barnes,Neutral,North Carolina".split(",")
	people << "Richard,Scott,Tea party,California".split(",")
	people << "Anne,Ruiz,Conservative,New York".split(",")
	people << "Todd,Weaver,Neutral,Florida".split(",")
	people << "Christina,Roberts,Tea party,Pennsylvania".split(",")
	people << "Wayne,Thomas,Tea party,California".split(",")
	people << "Paula,Stone,Conservative,California".split(",")
	people << "Alan,Willis,Liberal,Colorado".split(",")
	people << "Phillip,Lane,Liberal,Tennessee".split(",")
	people << "Nicole,Garrett,Neutral,Washington".split(",")
	people << "Steven,Jones,Liberal,Utah".split(",")
	people << "Amanda,Bailey,Conservative,North Carolina".split(",")
	people << "Craig,Bishop,Neutral,Florida".split(",")
	people << "Louise,Larson,Liberal,Mississippi".split(",")
	people << "Aaron,Palmer,Socialist,Illinois".split(",")
	people << "Christina,Little,Tea party,California".split(",")
	people << "Mary,Ruiz,Tea party,Hawaii".split(",")
	people << "Alan,Russell,Socialist,California".split(",")
	people << "Carl,Moore,Socialist,California".split(",")
	people << "Nancy,Greene,Neutral,Texas".split(",")
	people << "Martin,Burton,Liberal,California".split(",")
	people << "Philip,Simmons,Neutral,California".split(",")
	people << "Harry,Nguyen,Neutral,Arizona".split(",")
	people << "Ralph,Baker,Socialist,California".split(",")
	people << "Jonathan,Dixon,Socialist,District of Columbia".split(",")
	people << "Angela,Henderson,Conservative,Virginia".split(",")
	people << "Willie,Fuller,Liberal,Florida".split(",")
	people << "Carolyn,Frazier,Conservative,Virginia".split(",")
	people << "Cynthia,Jacobs,Liberal,Minnesota".split(",")
	people << "Michael,Hudson,Socialist,Washington".split(",")
	people << "Wanda,Roberts,Neutral,Florida".split(",")
	people << "Eric,Anderson,Conservative,Texas".split(",")
	people << "Rose,Hunt,Socialist,California".split(",")
	people << "Jose,Rice,Socialist,North Carolina".split(",")
	people << "Carolyn,Bell,Neutral,North Dakota".split(",")
	people << "Joyce,Flores,Socialist,Ohio".split(",")
	people << "Michelle,Wilson,Neutral,Virginia".split(",")
	people << "Laura,Long,Neutral,Colorado".split(",")
	people << "Katherine,Fisher,Socialist,Colorado".split(",")
	people << "Joe,Lane,Tea party,New York".split(",")
	people << "Janet,Chavez,Socialist,California".split(",")
	people << "Helen,Gonzalez,Liberal,Texas".split(",")
	people << "Paul,Larson,Neutral,District of Columbia".split(",")
	people << "Howard,Edwards,Socialist,California".split(",")
	people << "Maria,Nichols,Socialist,Georgia".split(",")
	people << "Timothy,Wheeler,Liberal,New Jersey".split(",")
	people << "Steven,Clark,Neutral,Ohio".split(",")
	people << "Justin,Hayes,Conservative,Virginia".split(",")
	people << "Judy,Mason,Liberal,Iowa".split(",")
	people << "Sarah,Carr,Tea party,Florida".split(",")
	people << "Phillip,Stephens,Neutral,Michigan".split(",")
	people << "Philip,Olson,Neutral,North Carolina".split(",")
	people << "Eric,Thompson,Liberal,Ohio".split(",")
	people << "Carol,Ramirez,Neutral,New York".split(",")
	people << "Douglas,Gonzalez,Conservative,Virginia".split(",")
	people << "Bruce,Turner,Socialist,Massachusetts".split(",")
	people << "Beverly,Cook,Liberal,New Jersey".split(",")
	people << "Emily,Franklin,Socialist,Missouri".split(",")
	people << "Nancy,Hunt,Liberal,Minnesota".split(",")
	people << "Jane,Mccoy,Conservative,Nebraska".split(",")
	people << "Ruby,Cole,Socialist,Virginia".split(",")
	people << "Ann,Turner,Liberal,California".split(",")
	people << "Denise,Wood,Liberal,Illinois".split(",")
	people << "George,Rogers,Neutral,Tennessee".split(",")
	people << "Kathryn,Cole,Socialist,California".split(",")
	people << "Janet,Carr,Liberal,Illinois".split(",")
	people << "Susan,Rice,Socialist,Massachusetts".split(",")
	people << "Victor,Dixon,Conservative,Texas".split(",")
	people << "Tina,Reyes,Socialist,Missouri".split(",")
	people << "Russell,Reynolds,Neutral,Florida".split(",")
	people << "Daniel,Harvey,Conservative,Maryland".split(",")
	people << "Dennis,Brown,Tea party,Florida".split(",")
	people << "Mary,Martinez,Liberal,Florida".split(",")
	people << "Pamela,Anderson,Tea party,Hawaii".split(",")
	people << "Barbara,Reid,Liberal,North Carolina".split(",")
	people << "Bonnie,Foster,Liberal,Pennsylvania".split(",")
	people << "Elizabeth,Ortiz,Conservative,Texas".split(",")
	people << "Louis,Williamson,Tea party,Ohio".split(",")
	people << "Paul,Wells,Liberal,Massachusetts".split(",")
	people << "Christina,Crawford,Socialist,California".split(",")
	people << "Christine,Rodriguez,Socialist,Kansas".split(",")
	people << "Patricia,Gilbert,Conservative,California".split(",")
	people << "Nicholas,Ross,Tea party,New Mexico".split(",")
	people << "Anthony,Nichols,Neutral,Texas".split(",")
	people << "Kenneth,Myers,Tea party,Michigan".split(",")
	people << "Diane,Jackson,Conservative,Louisiana".split(",")
	people << "Philip,Hanson,Conservative,Massachusetts".split(",")
	people << "Alan,Gonzalez,Neutral,Texas".split(",")
	people << "Jason,Medina,Liberal,Michigan".split(",")
	people << "Thomas,Murray,Tea party,Wisconsin".split(",")
	people << "Gerald,Olson,Conservative,California".split(",")
	people << "Jesse,Taylor,Liberal,California".split(",")
	people << "Daniel,Gomez,Liberal,Georgia".split(",")
	people << "Bobby,Palmer,Neutral,Texas".split(",")
	people << "Jesse,Webb,Liberal,New York".split(",")
	people << "George,Spencer,Conservative,Indiana".split(",")
	people << "Norma,Lynch,Liberal,Minnesota".split(",")
	people << "Christina,Taylor,Socialist,Pennsylvania".split(",")
	people << "Nicholas,Gomez,Neutral,Louisiana".split(",")
	people << "Wayne,Morales,Neutral,New York".split(",")
	people << "Diane,Martinez,Conservative,Minnesota".split(",")
	people << "Melissa,Turner,Tea party,Alabama".split(",")
	people << "Andrea,Carter,Conservative,North Carolina".split(",")
	people << "Melissa,Stewart,Liberal,Florida".split(",")
	people << "Arthur,Hicks,Conservative,West Virginia".split(",")
	people << "Johnny,Dunn,Liberal,Delaware".split(",")
	people << "Patrick,Pierce,Conservative,Texas".split(",")
	people << "George,Williams,Conservative,New York".split(",")
	people << "Christopher,Gomez,Neutral,Massachusetts".split(",")
	people << "Phyllis,Barnes,Tea party,Iowa".split(",")
	people << "Katherine,Hart,Neutral,Alabama".split(",")
	people << "Andrea,Fernandez,Liberal,North Carolina".split(",")
	people << "Raymond,Allen,Conservative,Virginia".split(",")
	people << "Fred,Price,Tea party,Florida".split(",")
	people << "Lori,Moore,Socialist,North Carolina".split(",")
	people << "Jack,Webb,Neutral,California".split(",")
	people << "Melissa,Parker,Socialist,California".split(",")
	people << "Cheryl,Greene,Neutral,California".split(",")
	people << "John,Roberts,Neutral,South Carolina".split(",")
	people << "Kenneth,Watson,Liberal,New York".split(",")
	people << "Stephen,Ferguson,Socialist,District of Columbia".split(",")
	people << "Kathleen,Hunter,Neutral,Virginia".split(",")
	people << "Joan,Diaz,Liberal,California".split(",")
	people << "Mark,Bradley,Conservative,California".split(",")
	people << "Robert,Hanson,Liberal,Illinois".split(",")
	people << "Irene,White,Conservative,Texas".split(",")
	people << "Joyce,Coleman,Tea party,Indiana".split(",")
	people << "Roy,Morris,Conservative,North Carolina".split(",")
	people << "Christina,Ramos,Liberal,Pennsylvania".split(",")
	people << "Jeremy,Butler,Tea party,New York".split(",")
	people << "Jennifer,Black,Socialist,Connecticut".split(",")
	people << "Michael,Johnston,Conservative,Iowa".split(",")
	people << "Earl,Fields,Neutral,New York".split(",")
	people << "Irene,Johnson,Tea party,Oklahoma".split(",")
	people << "Cheryl,Young,Tea party,Hawaii".split(",")
	people << "Catherine,Hudson,Neutral,California".split(",")
	people << "Barbara,Duncan,Liberal,Pennsylvania".split(",")
	people << "Aaron,Riley,Neutral,Texas".split(",")
	people << "Marie,Ruiz,Socialist,Texas".split(",")
	people << "Henry,Hayes,Liberal,Washington".split(",")
	people << "Jonathan,Baker,Neutral,North Carolina".split(",")
	people << "Martin,Sullivan,Socialist,Missouri".split(",")
	people << "Anne,Wilson,Liberal,Nevada".split(",")
	people << "Billy,Lewis,Tea party,Texas".split(",")
	people << "Julie,Warren,Conservative,Texas".split(",")
	people << "Thomas,Wells,Socialist,New York".split(",")
	people << "Jeremy,Medina,Socialist,Oklahoma".split(",")
	people << "Angela,Meyer,Socialist,California".split(",")
	people << "Louis,Peterson,Socialist,California".split(",")
	people << "Nicholas,Morales,Liberal,California".split(",")
	people << "Lawrence,Moore,Neutral,Texas".split(",")
	people << "Jerry,Daniels,Tea party,District of Columbia".split(",")
	people << "Dennis,Roberts,Socialist,Texas".split(",")
	people << "Kenneth,Williams,Neutral,Tennessee".split(",")
	people << "Jimmy,Collins,Socialist,New York".split(",")
	people << "Janet,Lynch,Neutral,Oklahoma".split(",")
	people << "Gregory,Ellis,Socialist,New Jersey".split(",")
	people << "Tammy,Medina,Conservative,Kansas".split(",")
	people << "Terry,Bishop,Tea party,New York".split(",")
	people << "Rachel,Matthews,Tea party,Alabama".split(",")
	people << "Henry,Ward,Conservative,Maryland".split(",")
	people << "Brenda,Torres,Socialist,Ohio".split(",")
	people << "Justin,Duncan,Liberal,Texas".split(",")
	people << "Christine,Elliott,Liberal,Indiana".split(",")
	people << "Annie,Harris,Socialist,Texas".split(",")
	people << "Carlos,Taylor,Conservative,Oregon".split(",")
	people << "Melissa,Chavez,Socialist,Missouri".split(",")
	people << "Walter,Burns,Conservative,Florida".split(",")
	people << "Ashley,Dean,Conservative,North Carolina".split(",")
	people << "Victor,Sullivan,Socialist,Florida".split(",")
	people << "Louise,Duncan,Neutral,Michigan".split(",")
	people << "Doris,Ramirez,Liberal,Kansas".split(",")
	people << "Antonio,Henry,Liberal,New York".split(",")
	people << "Jack,Bailey,Neutral,Oklahoma".split(",")
	people << "Anna,Thompson,Socialist,North Carolina".split(",")
	people << "Pamela,Tucker,Conservative,District of Columbia".split(",")
	people << "Douglas,Patterson,Conservative,Minnesota".split(",")
	people << "Lawrence,Mcdonald,Neutral,Tennessee".split(",")
	people << "Ruth,Banks,Conservative,Nevada".split(",")
	people << "Paul,Morgan,Socialist,Texas".split(",")
	people << "Steven,Johnson,Tea party,Alabama".split(",")
	people << "Tammy,Schmidt,Socialist,Texas".split(",")
	people << "Donna,Medina,Conservative,Minnesota".split(",")
	people << "Pamela,Murphy,Liberal,Illinois".split(",")
	people << "Nancy,Banks,Tea party,Oklahoma".split(",")
	people << "Harold,Cole,Neutral,Minnesota".split(",")
	people << "Helen,Sullivan,Tea party,California".split(",")
	people << "Billy,Long,Liberal,Virginia".split(",")
	people << "Sarah,Peters,Liberal,Texas".split(",")
	people << "Nicholas,Olson,Conservative,Virginia".split(",")
	people << "Betty,Woods,Neutral,Texas".split(",")
	people << "Larry,Brooks,Socialist,Pennsylvania".split(",")
	people << "Angela,Lopez,Neutral,Arkansas".split(",")
	people << "Gerald,Jenkins,Tea party,Illinois".split(",")
	people << "Evelyn,Ellis,Tea party,Minnesota".split(",")
	people << "Maria,Cook,Tea party,Wisconsin".split(",")
	people << "Howard,Owens,Conservative,Pennsylvania".split(",")
	people << "Christopher,Campbell,Socialist,Washington".split(",")
	people << "Ruby,Hudson,Liberal,Ohio".split(",")
	people << "Dorothy,Parker,Neutral,Hawaii".split(",")
	people << "Eric,Banks,Socialist,California".split(",")
	people << "Ann,Rice,Conservative,Arkansas".split(",")
	people << "Susan,Sanders,Socialist,Mississippi".split(",")
	people << "Harold,Reyes,Conservative,Michigan".split(",")
	people << "Joe,Robertson,Conservative,Washington".split(",")
	people << "David,Fowler,Socialist,New York".split(",")
	people << "Judy,Bradley,Socialist,New York".split(",")
	people << "Lisa,Gonzalez,Neutral,North Carolina".split(",")
	people << "Raymond,Ray,Liberal,California".split(",")
	people << "Gary,Fernandez,Tea party,Georgia".split(",")
	people << "Ryan,Daniels,Conservative,District of Columbia".split(",")
	people << "Christina,Ryan,Neutral,Utah".split(",")
	people << "Evelyn,Gutierrez,Conservative,California".split(",")
	people << "Bruce,Dixon,Liberal,Colorado".split(",")
	people << "Nancy,Carpenter,Socialist,New York".split(",")
	people << "Mark,Banks,Conservative,Alabama".split(",")
	people << "Brenda,Nelson,Socialist,Florida".split(",")
	people << "Dennis,Diaz,Liberal,Indiana".split(",")
	people << "Scott,Gilbert,Liberal,California".split(",")
	people << "Jack,Reyes,Conservative,Ohio".split(",")
	people << "Willie,Myers,Neutral,Florida".split(",")
	people << "Victor,Wright,Liberal,Texas".split(",")
	people << "Martin,Powell,Liberal,Texas".split(",")
	people << "Andrea,Ford,Liberal,Texas".split(",")
	people << "Steven,Lee,Neutral,Ohio".split(",")
	people << "Tina,Richardson,Socialist,Oklahoma".split(",")
	people << "Elizabeth,Morrison,Liberal,Michigan".split(",")
	people << "Brian,Welch,Neutral,Alabama".split(",")
	people.each do |person| 
		@voterList << Person.new(person[0],person[1],person[2],person[3])
	end
	people
end
def add_politicians
	politicians = []
	politicians << "Andrew,Olson,Repubican,Virginia".split(",")
	politicians << "Joe,Fuller,Democrat,Alaska".split(",")
	politicians << "Jeremy,Arnold,Democrat,California".split(",")
	politicians << "Shawn,Russell,Repubican,Connecticut".split(",")
	politicians << "Susan,Welch,Repubican,Florida".split(",")
	politicians << "Kathy,Hart,Repubican,Oregon".split(",")
	politicians << "Ralph,Cox,Repubican,Texas".split(",")
	politicians << "Shirley,Owens,Democrat,Missouri".split(",")
	politicians << "Doris,Williamson,Democrat,Missouri".split(",")
	politicians << "Tammy,Payne,Repubican,Florida".split(",")
	politicians << "Tina,Moreno,Democrat,Michigan".split(",")
	politicians << "Diane,Kennedy,Repubican,New Mexico".split(",")
	politicians << "Anne,Nguyen,Democrat,Nebraska".split(",")
	politicians << "Norma,Johnson,Repubican,Texas".split(",")
	politicians << "Karen,Perez,Democrat,Georgia".split(",")
	politicians << "Shawn,Parker,Democrat,Massachusetts".split(",")
	politicians << "Cheryl,Gray,Democrat,New Mexico".split(",")
	politicians << "Betty,Gilbert,Democrat,Ohio".split(",")
	politicians << "Tina,Dean,Democrat,Kansas".split(",")
	politicians << "Wayne,Kennedy,Repubican,Delaware".split(",")
	politicians << "Debra,Ryan,Democrat,Washington".split(",")
	politicians << "Jacqueline,Alexander,Democrat,Virginia".split(",")
	politicians << "Judy,Powell,Democrat,California".split(",")
	politicians << "Arthur,Jenkins,Repubican,Texas".split(",")
	politicians << "Joan,Washington,Repubican,Louisiana".split(",")
	politicians.each do |politician| 
	@voterList << Politician.new(politician[0],politician[1],politician[2],politician[3])
end
end
# p add_people